# Generated by Django 5.0.4 on 2024-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAppWeb', '0002_remove_task_end_date_remove_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
