# Generated by Django 5.0.4 on 2024-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAppWeb', '0003_task_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stopwatch',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timeTracking',
            field=models.JSONField(null=True),
        ),
    ]
