# Generated by Django 5.0.4 on 2024-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAppWeb', '0004_task_stopwatch_task_timetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='columnId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
