# Generated by Django 5.0.4 on 2024-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAppWeb', '0006_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='task',
            name='columnId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stickers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stopwatch',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeTracking',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='dict_info',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
