# Generated by Django 5.0.4 on 2024-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAppWeb', '0008_rename_task_taskyougile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPlanfix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_info', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
